// lib/color-defaults.ts
// Full default palette for every color CSS var. Shared by the color settings
// page and the color inspector so both always show the same "current" value.

export const LIGHT_DEFAULTS: Record<string, string> = {
  '--background': '#f0f7fc', '--foreground': '#1c1c1c', '--card': '#f5f9fc',
  '--card-foreground': '#1c1c1c', '--primary': '#2a2a2a', '--primary-foreground': '#f8f8f8',
  '--secondary': '#e6edf5', '--secondary-foreground': '#2a2a2a', '--muted': '#e6edf5',
  '--muted-foreground': '#727272', '--accent': '#e6edf5', '--accent-foreground': '#2a2a2a',
  '--destructive': '#d94f37', '--border': '#d5e0ec', '--input': '#d5e0ec',
  '--shift-others-bg': '#dde8f0', '--shift-others-date-bg': '#d0dde8',
  '--shift-others-date-border': '#bdd0e0', '--shift-own-empty-bg': '#e4e4f0',
  '--shift-own-empty-date-bg': '#d8d8ec', '--shift-own-empty-border': '#c8c8e0',
  '--shift-own-interest-bg': '#dcfce7', '--shift-own-interest-date-bg': '#bbf7d0',
  '--shift-own-interest-border': '#86efac', '--shift-highlight-bg': '#fef9e7',
  '--shift-highlight-date-bg': '#fef3c7', '--pill-mattina-bg': '#dbeafe',
  '--pill-mattina-text': '#1d4ed8', '--pill-pomeriggio-bg': '#fef3c7',
  '--pill-pomeriggio-text': '#b45309', '--pill-notte-bg': '#ede9fe',
  '--pill-notte-text': '#6d28d9',
  '--banner-impersonate-bg': '#f97316', '--banner-impersonate-text': '#ffffff',
  '--match-panel-bg': '#eaf7ee', '--match-panel-border': '#a8d5b4',
  '--match-text': '#16a34a', '--match-badge-bg': '#1a4d2e',
  '--match-action-bg': '#15803d', '--match-action-text': '#ffffff',
  '--match-count-text': '#d97706', '--match-pos-text': '#65a30d', '--match-none-text': '#16a34a',
  '--chain-panel-bg': '#ede9f8', '--chain-panel-border': '#c8aaed',
  '--chain-text': '#6d28d9', '--chain-badge-bg': '#3d1a7a',
  '--chain-action-bg': '#6d28d9', '--chain-action-text': '#ffffff',
  '--chain-node-text': '#7c3aed',
  '--chip-selected-bg': '#38bdf8', '--chip-selected-text': '#ffffff', '--chip-selected-border': '#38bdf8',
  '--offered-box-bg': '#f0f9ff', '--offered-box-border': '#bae6fd',
  '--offered-box-label': '#0284c7', '--offered-box-value': '#0c4a6e',
  '--my-period-border': '#38bdf8', '--my-period-header-bg': '#e0f2fe',
  '--my-period-content-bg': '#f0f9ff', '--my-period-text': '#0c4a6e', '--my-period-dot': '#0ea5e9',
  '--period-1-pill-bg': '#d1fae5', '--period-1-pill-text': '#065f46',
  '--period-2-pill-bg': '#fef9c3', '--period-2-pill-text': '#854d0e',
  '--period-3-pill-bg': '#fef3c7', '--period-3-pill-text': '#92400e',
  '--period-4-pill-bg': '#ffedd5', '--period-4-pill-text': '#9a3412',
  '--period-5-pill-bg': '#ffe4e6', '--period-5-pill-text': '#9f1239',
  '--period-6-pill-bg': '#ede9fe', '--period-6-pill-text': '#5b21b6',
  '--period-1-card-border': '#6ee7b7', '--period-1-card-header': '#d1fae5', '--period-1-card-content': '#ecfdf5',
  '--period-2-card-border': '#fde047', '--period-2-card-header': '#fef9c3', '--period-2-card-content': '#fefce8',
  '--period-3-card-border': '#fcd34d', '--period-3-card-header': '#fef3c7', '--period-3-card-content': '#fffbeb',
  '--period-4-card-border': '#fdba74', '--period-4-card-header': '#ffedd5', '--period-4-card-content': '#fff7ed',
  '--period-5-card-border': '#fda4af', '--period-5-card-header': '#ffe4e6', '--period-5-card-content': '#fff1f2',
  '--period-6-card-border': '#c4b5fd', '--period-6-card-header': '#ede9fe', '--period-6-card-content': '#f5f3ff',
  '--dialog-pill-mattina-border': '#bfdbfe', '--dialog-pill-mattina-active-bg': '#dbeafe', '--dialog-pill-mattina-active-border': '#60a5fa',
  '--dialog-pill-pomeriggio-border': '#fde68a', '--dialog-pill-pomeriggio-active-bg': '#fef3c7', '--dialog-pill-pomeriggio-active-border': '#f59e0b',
  '--dialog-pill-notte-border': '#e9d5ff', '--dialog-pill-notte-active-bg': '#ede9fe', '--dialog-pill-notte-active-border': '#a78bfa',
  '--badge-noni-bg': '#f3e8ff', '--badge-noni-text': '#7e22ce',
  '--badge-dco-bg': '#dbeafe', '--badge-dco-text': '#1d4ed8',
  '--interest-date-color': '#4ade80', '--own-name-color': '#854d0e',
  '--interest-btn-bg': '#16a34a', '--feedback-check-color': '#22c55e',
  '--desk-schedule-border': '#bae6fd',
  '--sala-highlight-border': '#38bdf8', '--sala-highlight-ring': 'rgba(14,165,233,0.30)',
  '--sala-own-badge-bg': '#dbeafe', '--sala-own-badge-border': '#38bdf8', '--sala-own-badge-text': '#0369a1',
}

export const DARK_DEFAULTS: Record<string, string> = {
  '--background': '#1a1a1a', '--foreground': '#f5f5f5', '--card': '#282828',
  '--card-foreground': '#f5f5f5', '--primary': '#ebebeb', '--primary-foreground': '#282828',
  '--secondary': '#363636', '--secondary-foreground': '#f5f5f5', '--muted': '#363636',
  '--muted-foreground': '#b5b5b5', '--accent': '#363636', '--accent-foreground': '#f5f5f5',
  '--destructive': '#d94f37', '--border': '#2e2e2e', '--input': '#2e2e2e',
  '--shift-others-bg': '#1a1a1a', '--shift-others-date-bg': '#252525',
  '--shift-others-date-border': '#2e2e2e', '--shift-own-empty-bg': '#2a2a35',
  '--shift-own-empty-date-bg': '#32323f', '--shift-own-empty-border': '#3a3a4a',
  '--shift-own-interest-bg': '#162416', '--shift-own-interest-date-bg': '#1a2e1a',
  '--shift-own-interest-border': '#22c55e', '--shift-highlight-bg': '#2a2000',
  '--shift-highlight-date-bg': '#332800', '--pill-mattina-bg': '#1e3a5f',
  '--pill-mattina-text': '#60a5fa', '--pill-pomeriggio-bg': '#3b2300',
  '--pill-pomeriggio-text': '#fbbf24', '--pill-notte-bg': '#2d1b69',
  '--pill-notte-text': '#a78bfa',
  '--banner-impersonate-bg': '#ea580c', '--banner-impersonate-text': '#ffffff',
  '--match-panel-bg': '#0e2e1a', '--match-panel-border': '#3d7a4d',
  '--match-text': '#4ade80', '--match-badge-bg': '#142d1e',
  '--match-action-bg': '#16a34a', '--match-action-text': '#ffffff',
  '--match-count-text': '#fbbf24', '--match-pos-text': '#a3e635', '--match-none-text': '#86efac',
  '--chain-panel-bg': '#2a1050', '--chain-panel-border': '#5a28a0',
  '--chain-text': '#a78bfa', '--chain-badge-bg': '#2e1260',
  '--chain-action-bg': '#7c3aed', '--chain-action-text': '#ffffff',
  '--chain-node-text': '#c4b5fd',
  '--chip-selected-bg': '#18181b', '--chip-selected-text': '#ffffff', '--chip-selected-border': '#3f3f46',
  '--offered-box-bg': '#082f49', '--offered-box-border': '#0c4a6e',
  '--offered-box-label': '#38bdf8', '--offered-box-value': '#e0f2fe',
  '--my-period-border': '#0284c7', '--my-period-header-bg': '#0d2535',
  '--my-period-content-bg': '#061820', '--my-period-text': '#e0f2fe', '--my-period-dot': '#0ea5e9',
  '--period-1-pill-bg': '#064e3b', '--period-1-pill-text': '#6ee7b7',
  '--period-2-pill-bg': '#422006', '--period-2-pill-text': '#fde047',
  '--period-3-pill-bg': '#451a03', '--period-3-pill-text': '#fcd34d',
  '--period-4-pill-bg': '#431407', '--period-4-pill-text': '#fb923c',
  '--period-5-pill-bg': '#4c0519', '--period-5-pill-text': '#fb7185',
  '--period-6-pill-bg': '#2e1065', '--period-6-pill-text': '#c4b5fd',
  '--period-1-card-border': '#047857', '--period-1-card-header': '#064e3b', '--period-1-card-content': '#022c22',
  '--period-2-card-border': '#a16207', '--period-2-card-header': '#422006', '--period-2-card-content': '#421e0f',
  '--period-3-card-border': '#b45309', '--period-3-card-header': '#451a03', '--period-3-card-content': '#451a03',
  '--period-4-card-border': '#c2410c', '--period-4-card-header': '#431407', '--period-4-card-content': '#431407',
  '--period-5-card-border': '#be123c', '--period-5-card-header': '#4c0519', '--period-5-card-content': '#4c0519',
  '--period-6-card-border': '#6d28d9', '--period-6-card-header': '#2e1065', '--period-6-card-content': '#2e1065',
  '--dialog-pill-mattina-border': '#1e3a5f', '--dialog-pill-mattina-active-bg': '#1e3a5f', '--dialog-pill-mattina-active-border': '#3b82f6',
  '--dialog-pill-pomeriggio-border': '#3b2300', '--dialog-pill-pomeriggio-active-bg': '#3b2300', '--dialog-pill-pomeriggio-active-border': '#d97706',
  '--dialog-pill-notte-border': '#2d1b69', '--dialog-pill-notte-active-bg': '#2d1b69', '--dialog-pill-notte-active-border': '#7c3aed',
  '--badge-noni-bg': '#2e1065', '--badge-noni-text': '#d8b4fe',
  '--badge-dco-bg': '#1e3a5f', '--badge-dco-text': '#93c5fd',
  '--interest-date-color': '#4ade80', '--own-name-color': '#fef08a',
  '--interest-btn-bg': '#16a34a', '--feedback-check-color': '#22c55e',
  '--desk-schedule-border': '#2e2e2e',
  '--sala-highlight-border': '#fbbf24', '--sala-highlight-ring': 'rgba(245,158,11,0.25)',
  '--sala-own-badge-bg': 'rgba(66,32,6,0.35)', '--sala-own-badge-border': '#fbbf24', '--sala-own-badge-text': '#fde047',
}

// Single source of truth for the browser chrome (meta theme-color) colors.
// Derived from the --background defaults so they can never drift.
export const LIGHT_BACKGROUND = LIGHT_DEFAULTS['--background']
export const DARK_BACKGROUND = DARK_DEFAULTS['--background']
